import { mountResponsiveTextBox } from './celticBox.js';
import { celticTextboxData } from './config.js';

// --- Extracted Helper Functions ---

function updateDescriptionText(state, dom, glossaryData) {
    const isHorizontalSettled = Math.abs(state.horizontalAngle - state.targetHorizontalAngle) < 0.5;
    const currentCategory = updateActiveIndex(state);
    const currentVertAngle = state.verticalAngles[currentCategory];
    const targetVertAngle = state.targetVerticalAngles[currentCategory];
    const isVerticalSettled = Math.abs(currentVertAngle - targetVertAngle) < 0.5;

    // Dynamically grab the container generated by mountResponsiveTextBox
    const targetEl = dom.bottomDiv.querySelector('.hex-box-content');
    
    // If the ResizeObserver is currently wiping/rebuilding the box, skip this frame
    if (!targetEl) return; 

    // --- NEW: Re-apply your custom class if the ResizeObserver wiped it ---
    if (!targetEl.classList.contains('description-text')) {
        targetEl.classList.add('description-text');
        
        // Instantly apply the 'faded' state if the text shouldn't be visible right now
        if (!state.textIsVisible) {
            targetEl.classList.add('faded');
        }
    }

    // If scrolling or dragging is happening, fade out
    if (!isHorizontalSettled || !isVerticalSettled || state.isDragging) {
        if (state.textIsVisible) {
            targetEl.classList.add('faded');
            state.textIsVisible = false;
        }
        return;
    }

    // If settled, determine the active item
    const activeItemIndex = Math.round(-targetVertAngle / state.thetaX);
    const dataIndex = activeItemIndex - state.paddingCount; // Offset the blank padding
    
    const categoryData = glossaryData.categories[currentCategory];
    let newText = "";

    // Safely extract the description from the JSON structure
    if (categoryData && dataIndex >= 0 && dataIndex < categoryData.items.length) {
        newText = categoryData.items[dataIndex].description;
    }

    // Only update the DOM if the text has actually changed
    if (targetEl.textContent !== newText) {
        targetEl.textContent = newText;
    }

    // Fade in once the text is ready
    if (!state.textIsVisible && newText !== "") {
        targetEl.classList.remove('faded');
        state.textIsVisible = true;
    }
}

function calculateVisibility(state, dom) {
    dom.panelsArray.forEach((panel, i) => {
        let worldAngle = (i * state.thetaY + state.horizontalAngle) % 360;
        if (worldAngle < 0) worldAngle += 360;
        
        let diff = Math.min(worldAngle, 360 - worldAngle); 
        const titleEl = panel.querySelector('.panel-title');
        const itemEls = panel.querySelectorAll('.item');

        // 1. Calculate raw opacity
        let rawOpacity = (180 - diff) / 180;
        
        // 2. Clean the number: Round to 3 decimal places.
        // This instantly converts e-15 numbers to exactly 0, and 0.9999 to 1.
        let panelOpacity = Math.round(rawOpacity * 1000) / 1000;

        // Snap edge cases just in case you want strict 0.001 to act as 0
        if (panelOpacity < 0.002) panelOpacity = 0;
        if (panelOpacity > 0.998) panelOpacity = 1;

        titleEl.style.opacity = panelOpacity;

        const currentAngle = state.verticalAngles[i];
        const activeItemIndex = Math.round(-currentAngle / state.thetaX);
        const VISIBLE_RANGE = 5;

        itemEls.forEach((item, itemIndex) => {
            const distance = Math.abs(itemIndex - activeItemIndex);

            if (distance > VISIBLE_RANGE) {
                // 3. Performance boost: Only touch the DOM if it actually needs to change
                if (item.style.visibility !== 'hidden') {
                    item.style.visibility = 'hidden';
                    item.style.opacity = 0;
                }
            } else {
                if (item.style.visibility !== 'visible') {
                    item.style.visibility = 'visible';
                }
                // Apply the clean, rounded opacity
                item.style.opacity = panelOpacity;
            }
        });
    });
}

function updateActiveIndex(state) {
    let normalized = state.targetHorizontalAngle % 360;
    if (normalized < 0) normalized += 360;
    state.activeCategoryIndex = Math.round((360 - normalized) % 360 / state.thetaY) % state.totalCategories;
    return state.activeCategoryIndex;
}

function snapCarousel(state) {
    if (state.dragAxis === 'x' || state.dragAxis === null) {
        state.targetHorizontalAngle = Math.round(state.targetHorizontalAngle / state.thetaY) * state.thetaY;
        updateActiveIndex(state);
    }
    
    if (state.dragAxis === 'y' || state.dragAxis === null) {
        const tX = state.thetaXArray[state.activeCategoryIndex];
        const bounds = state.verticalBounds[state.activeCategoryIndex];
        
        let snappedX = Math.round(state.targetVerticalAngles[state.activeCategoryIndex] / tX) * tX;
        state.targetVerticalAngles[state.activeCategoryIndex] = Math.max(bounds.min, Math.min(bounds.max, snappedX));
    }
    
    state.dragAxis = null;
}

function renderFrame(state, dom, glossaryData) { // <-- 1. Accept the argument
    state.horizontalAngle += (state.targetHorizontalAngle - state.horizontalAngle) * 0.1;
    dom.horizontalCarousel.style.transform = `rotateY(${state.horizontalAngle}deg)`;
    
    state.verticalAngles.forEach((angle, i) => {
        state.verticalAngles[i] += (state.targetVerticalAngles[i] - state.verticalAngles[i]) * 0.1;
        dom.verticalCylinders[i].style.transform = `rotateX(${state.verticalAngles[i]}deg)`;
    });

    calculateVisibility(state, dom);
    updateDescriptionText(state, dom, glossaryData); 

    // <-- 2. Pass the data into the recursive loop for the next frame
    state.animationFrameId = requestAnimationFrame(() => renderFrame(state, dom, glossaryData)); 
}

function handleResize(entries, state, dom) {
    for (let entry of entries) {
        const width = entry.contentRect.width;
        const safeTextWidth = width * 0.85;
        const radiusXCalc = Math.max(60, Math.min(80, width * 0.22));
        
        const radTheta = (state.thetaX / 2) * (Math.PI / 180);
        const itemHeight = 2 * radiusXCalc * Math.tan(radTheta);
        
        const maxFontSizeByWidth = safeTextWidth / (state.maxChars * 0.6);
        const maxFontSizeByHeight = itemHeight * 0.75;
        const finalFontSize = Math.max(12, Math.min(maxFontSizeByWidth, maxFontSizeByHeight));

        dom.masterScene.style.setProperty('--dynamic-font-size', `${finalFontSize}px`);
        dom.masterScene.style.setProperty('--item-height', `${itemHeight}px`);
        dom.masterScene.style.setProperty('--radius-x', `${radiusXCalc}px`);

        const dynamicPanelWidth = width * 0.75; 
        let newRadiusY = Math.round((dynamicPanelWidth / 2) / Math.tan(Math.PI / state.totalCategories));
        newRadiusY = Math.max(newRadiusY, width * 0.4); 

        dom.panelsArray.forEach((panel, index) => {
            panel.style.transform = `rotateY(${index * state.thetaY}deg) translateZ(${newRadiusY}px)`;
        });
    }
}

// --- Extracted Event Handlers ---

function handleWheelEvent(e, state) {
    e.preventDefault();

    // Adjusted multipliers to make wheel scrolling significantly slower and smoother
    if (Math.abs(e.deltaX) > Math.abs(e.deltaY)) {
        state.targetHorizontalAngle -= e.deltaX * 0.25; 
        state.dragAxis = 'x';
    } else {
        const bounds = state.verticalBounds[state.activeCategoryIndex];
        let newTarget = state.targetVerticalAngles[state.activeCategoryIndex] - e.deltaY * 0.25; 
        state.targetVerticalAngles[state.activeCategoryIndex] = Math.max(bounds.min - 15, Math.min(bounds.max + 15, newTarget));
        state.dragAxis = 'y';
    }

    clearTimeout(state.scrollTimeout);
    state.scrollTimeout = setTimeout(() => snapCarousel(state), 150);
}

function handlePointerDownEvent(e, state) {
    state.isDragging = true;
    state.hasDragged = false;
    
    // Support both Touch and Mouse coords
    const coords = e.touches ? e.touches[0] : e;
    state.startX = coords.clientX;
    state.startY = coords.clientY;
    state.dragAxis = null;
    
    clearTimeout(state.scrollTimeout);
}

function handlePointerMoveEvent(e, state) {
    if (!state.isDragging) return;
    
    const coords = e.touches ? e.touches[0] : e;
    const currentX = coords.clientX;
    const currentY = coords.clientY;
    const deltaX = currentX - state.startX;
    const deltaY = currentY - state.startY;

    if (Math.abs(deltaX) > 5 || Math.abs(deltaY) > 5) {
        state.hasDragged = true;
    }

    if (!state.dragAxis) {
        if (Math.abs(deltaX) > 5 || Math.abs(deltaY) > 5) {
            state.dragAxis = Math.abs(deltaX) > Math.abs(deltaY) ? 'x' : 'y';
        } else {
            return; 
        }
    }

    if (state.dragAxis === 'x') {
        state.targetHorizontalAngle += deltaX * 0.5;
        state.startX = currentX;
    } else {
        const bounds = state.verticalBounds[state.activeCategoryIndex];
        let newTarget = state.targetVerticalAngles[state.activeCategoryIndex] - deltaY * 0.5;
        state.targetVerticalAngles[state.activeCategoryIndex] = Math.max(bounds.min - 15, Math.min(bounds.max + 15, newTarget));
        state.startY = currentY;
    }
}

function handlePointerUpEvent(state) {
    if (!state.isDragging) return;
    state.isDragging = false;
    snapCarousel(state); 
}

function handleItemClick(i, index, itemText, state) {
    if (state.hasDragged) return; 

    if (state.activeCategoryIndex === index) {
        const currentAngle = state.targetVerticalAngles[index];
        const activeItemIndex = Math.round(-currentAngle / state.thetaX);
        
        if (i === activeItemIndex) {
            console.log(`Active item clicked: ${itemText}`);
        }
    }
}

// --- Main Render Function ---

export function renderGlossaryPage(container, glossaryData) {
    container.innerHTML = '';
    
    // --- Data Setup ---
    const PADDING_COUNT = 5;

    // Dynamically calculate padding and map data from the JSON
    const parsedGlossary = glossaryData.categories.map(category => {
        const pad = Array(PADDING_COUNT).fill({ name: '', description: '' });
        return {
            title: category.title,
            originalItems: category.items,
            items: [...pad, ...category.items, ...pad] 
        };
    });
const initialVerticalAngles = parsedGlossary.map(() => -(PADDING_COUNT * 24));

    // --- State Object ---
    const state = {
        horizontalAngle: 0,
        targetHorizontalAngle: 0,
        activeCategoryIndex: 0,
        isDragging: false,
        hasDragged: false,
        startX: 0,
        startY: 0,
        dragAxis: null,
        scrollTimeout: null,
        totalCategories: parsedGlossary.length,
        thetaY: 360 / parsedGlossary.length,
        thetaX: 24,
        paddingCount: PADDING_COUNT, // <-- Added for description indexing
        textIsVisible: true,         // <-- Added to track fade state
        maxChars: 20, // Default fallback if needed
        verticalAngles: [...initialVerticalAngles],
        targetVerticalAngles: [...initialVerticalAngles],
        verticalBounds: [],
        thetaXArray: [],
        animationFrameId: null
    };

    // --- DOM Object ---
    const dom = {
        masterScene: document.createElement('div'),
        horizontalCarousel: document.createElement('div'),
        panelsArray: [],
        verticalCylinders: [],
        bottomDiv: document.createElement('div')
    };

    const glossaryContent = document.createElement('div');
    glossaryContent.className = 'glossary-content';
    dom.masterScene.className = 'master-scene';
    dom.horizontalCarousel.className = 'horizontal-carousel';

    // --- DOM Construction ---
    parsedGlossary.forEach((data, index) => {
        const panel = document.createElement('div');
        panel.className = 'carousel-panel';

        const title = document.createElement('div');
        title.className = 'panel-title';
        title.textContent = data.title;
        panel.appendChild(title);

        const cylinder = document.createElement('div');
        cylinder.className = 'cylinder';

        state.thetaXArray.push(state.thetaX);

        const startBound = -(PADDING_COUNT * state.thetaX);
        const endBound = -((PADDING_COUNT + data.originalItems.length - 1) * state.thetaX);
        state.verticalBounds.push({ max: startBound, min: endBound });

        data.items.forEach((itemObj, i) => {
            const itemEl = document.createElement('div');
            itemEl.className = 'item'; 
            itemEl.textContent = itemObj.name; // Pulling 'name' from JSON
            
            itemEl.style.transform = `rotateX(${i * state.thetaX}deg) translateZ(var(--radius-x))`;
            itemEl.addEventListener('click', () => handleItemClick(i, index, itemObj.name, state));
            
            cylinder.appendChild(itemEl);
        });

        panel.appendChild(cylinder);
        dom.horizontalCarousel.appendChild(panel);
        
        dom.verticalCylinders.push(cylinder);
        dom.panelsArray.push(panel);
    });

    dom.masterScene.appendChild(dom.horizontalCarousel);
    glossaryContent.appendChild(dom.masterScene);

// --- Bottom Div Assembly ---
    dom.bottomDiv.className = 'panel-bottom';
    
    // Mount the responsive text box. 
    // We pass an empty string because updateDescriptionText will populate it immediately.
    mountResponsiveTextBox(celticTextboxData, dom.bottomDiv, ""); 
    
    glossaryContent.appendChild(dom.bottomDiv);
    container.appendChild(glossaryContent);

    // Initial text population
    updateDescriptionText(state, dom, glossaryData);

    // --- Initialization & Observers ---
    state.animationFrameId = requestAnimationFrame(() => renderFrame(state, dom, glossaryData));

    const resizeObserver = new ResizeObserver((entries) => handleResize(entries, state, dom));
    resizeObserver.observe(container);

    // --- Event Listeners (Bound with State/DOM) ---
    const onWheel = (e) => handleWheelEvent(e, state);
    const onPointerDown = (e) => handlePointerDownEvent(e, state);
    const onPointerMove = (e) => handlePointerMoveEvent(e, state);
    const onPointerUp = () => handlePointerUpEvent(state);

    dom.masterScene.addEventListener('wheel', onWheel, { passive: false });
    
    // Touch Events
    dom.masterScene.addEventListener('touchstart', onPointerDown, { passive: false });
    dom.masterScene.addEventListener('touchmove', onPointerMove, { passive: false });
    dom.masterScene.addEventListener('touchend', onPointerUp);
    
    // Mouse Events for Desktop Dragging
    dom.masterScene.addEventListener('mousedown', onPointerDown);
    // Bind move/up to window so dragging doesn't break if the cursor leaves the scene element
    window.addEventListener('mousemove', onPointerMove);
    window.addEventListener('mouseup', onPointerUp);

    // --- Cleanup Return ---
    return function destroyGlossaryPage() {
        resizeObserver.disconnect();
        cancelAnimationFrame(state.animationFrameId);
        
        dom.masterScene.removeEventListener('wheel', onWheel);
        
        dom.masterScene.removeEventListener('touchstart', onPointerDown);
        dom.masterScene.removeEventListener('touchmove', onPointerMove);
        dom.masterScene.removeEventListener('touchend', onPointerUp);
        
        dom.masterScene.removeEventListener('mousedown', onPointerDown);
        window.removeEventListener('mousemove', onPointerMove);
        window.removeEventListener('mouseup', onPointerUp);
        
        clearTimeout(state.scrollTimeout);
        container.innerHTML = '';
    };
}